<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- <link rel="icon" href="../../../../favicon.ico"> -->

    <title>Batterea rehome an animal</title>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

    <style type="text/css">
      .jumbotron {
        background-color: #0054a3;
      }
      .display-3, .lead {
        color: #FFF;
      }
      .chatbot {
        min-height: 450px;
      }
    </style>

  </head>

  <body>

    <div class="container">
      <main role="main">

        <div class="jumbotron">
          <div class="container">
            <div class="row">
              <div class="col-lg-8">
                <h1 class="display-3">Rehome an animal</h1>
                <p class="lead"></p>
              </div>
              <div class="col-lg-4">
                  <img class="img-fluid" src="cat.jpeg">
              </div>
            </div>
          </div>
        </div>

        <div class="row marketing">
          <div class="col-lg-4">
              <iframe
                      width="350"
                      height="430"
                      src="https://console.dialogflow.com/api-client/demo/embedded/ac3f4781-ef03-4e22-8e16-49fc78ea630c">
              </iframe>
          </div>          
        </div>
        <div class="container">
          <div class="row">

          </div>
        </div>
      </main>
    </div> <!-- /container -->
  </body>
</html>
